-- Tighten Ava schema exposure: remove anon access and keep authenticated/service-role only.

REVOKE ALL ON SCHEMA ava FROM anon;
GRANT USAGE ON SCHEMA ava TO authenticated, service_role;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA ava FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ava TO authenticated, service_role;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ava FROM anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ava TO authenticated, service_role;

REVOKE ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA ava FROM anon;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA ava TO authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ava
  REVOKE ALL ON TABLES FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ava
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ava
  REVOKE ALL ON SEQUENCES FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ava
  GRANT USAGE, SELECT ON SEQUENCES TO authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ava
  REVOKE ALL ON ROUTINES FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ava
  GRANT EXECUTE ON ROUTINES TO authenticated, service_role;

NOTIFY pgrst, 'reload config';

